### ISSUE TITLE
Start error on Centos 7 

### ISSUE THREAD

**Issue by Montereytony** [ItsTheChickenMan/thechat3d#2]
When starting, I get:

 node server.js
/var/www/html/new/chat4/node_modules/ws/lib/websocket.js:345
      ...options
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/www/html/new/chat4/node_modules/ws/index.js:3:19)

**Comment by pxdal** [comment]
Hi @Montereytony ,
According to [this issue](https://github.com/uport-project/uport-cli-client/issues/2#issuecomment-371264736), the object spread operator (...) was not supported until node version 8.2.1 (with `--harmony` flag, and then without flag 8.6.0).  If you're running a lower version of node, I would try upgrading and seeing if that fixes the problem.  I'll also look into supporting older versions of node.

**Comment by Montereytony** [comment]
Thank you @ItsTheChickenMan !  I upgraded and it started right up!  

[root@mate chat4]# node server.js
Reading map data from map.json...
Loading map data...
Parsing map data...
14 objects parsed, map ready.
server open, listening

**Comment by pxdal** [comment]
Great!  Thanks for checking out this project!
